### ISSUE TITLE
Implement Heartbeat in codegen

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/canzero-codegen#21]

**Comment by kistenklaus** [comment]
Nodes are sending heatbeats at 100ms intervals, but they are not yet handling received heartbeats

**Comment by arrowtip** [comment]
One heartbeat check task, running at tick period of say 50ms that increments all heartbeat counters by one.
Each node has a max tick count it is allowed to reach before an error is generated.
Hearbeat receive task resets tick count to zero.

Max response time should be < heartbeat period + heartbeat tick period.
Only one task required to check all heartbeats.
Tick counter can be stored in array with size > (number nodes) to allow for dynamic heartbeats (registering new heartbeats at runtime)

**Comment by arrowtip** [comment]
static heartbeats implemented, including activation only after first receive
