### ISSUE TITLE
Test Heartbeat end to end

### ISSUE THREAD

**Issue by kistenklaus** [mu-zero-HYPERLOOP/canzero-codegen#23]

**Comment by kistenklaus** [comment]
Any node error should be detected by all other nodes. Within less than 200ms and the handling should try to be synchronous across 
nodes. I don't know how hard the second condition is to implement

**Comment by arrowtip** [comment]
heartbeat tested on x86 over socket can between two nodes.

**Comment by arrowtip** [comment]
tests on x86:
1) network of three nodes -> node1 shutdown -> node2 and node3 register timeout
2) network of three nodes -> node1 unregisters from heartbeat -> node2 and node3 do not register timeout -> node1 reregisters 
    heartbeat -> node1 shutdown -> node2 and node3 register timeout
3) network of three nodes -> control panel sends dynamic heartbeat -> control panel shutdown -> all other nodes register timeout
4) network of three nodes -> control panel sends dynamic heartbeat -> frontend freezes -> all other nodes register timeout
5) network of three nodes -> control panel sends dynamic heartbeat -> deadlock occurs -> all other nodes register timeout
6) network of three nodes -> node1 send heartbeat message with max ticks_next value -> node1 stops sending heartbeats -> timeout only occurs after very long time

**Comment by arrowtip** [comment]
1) check
2) check
3) check
4) check
5) check
6) check
